### ISSUE TITLE
[FIX] Gmail SMTP 포트 수정, 엑세스토큰 유효시간 변경 및 CORS 변경

### ISSUE THREAD

**Issue by rhkr8521** [Charge-Control/Backend#13]
## 🚀 About Issue 🚀

Gmail SMTP포트 설정 에러로 정상적인 포트로 변경, 엑세스토큰 유효시간을 일주일로 변경, CORS 도메인을 변경합니다.

## ✅ Todo 

- [x] SMTP포트 설정 에러 로직 수정
- [x] 엑세스토큰 유효시간 변경
- [x] CORS 도메인 변경
