### ISSUE TITLE
[FEAT] 위반사항 전체, 상세조회 기능

### ISSUE THREAD

**Issue by rhkr8521** [Charge-Control/Backend#7]
## 🚀 About Issue 🚀

위반사항 전체, 상세조회 기능을 개발합니다.

## ✅ Todo 

- [x] 위반사항 엔티티 작성
- [x] 위반사항 전체정보 조회 기능 구현
- [x] 위반사항 상세정보 조회 기능 구현
